---
title: perlatranquilla
baseURL: "/"
params:
  palette: yellow
  header:
    title: PerlaTranquilla
    tagline: Het nieuwe thuis van Rob en Monique
    logo_img: images/perla.png
    bg_img: "/images/000029.jpg"
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links: []
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
