---
title: perla tranquilla
baseURL: "/"
params:
  palette: yellow
  header:
    title: Perla Tranquilla
    tagline: Het nieuwe thuis van Rob en Monique
    logo_img: images/logo.png
    bg_img: "/images/000029.jpg"
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
menu:
  main:
  - url: https://photos.app.goo.gl/wiRAWTnU8Rzh6gyC6
    name: Foto's
    weight: 2
